{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Untitled13.ipynb",
      "provenance": [],
      "authorship_tag": "ABX9TyNt7YpleLHR4glaub5/Yobb",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rpalmac/Automatizacion-de-Infraestructura-Digital/blob/main/Ejercicio3.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "9Blks-Na8zb2",
        "outputId": "83ed6176-e47b-44bb-ccb3-402a76d92aa3"
      },
      "source": [
        "def get_phone(file, client):\n",
        "    '''\n",
        "    Función que devuelve el teléfono de un cliente de un fichero dado.\n",
        "    Parámetros:\n",
        "        file: Es un fichero con los nombres y teléfonos de clientes.\n",
        "        client: Es una cadena con el nombre del cliente.\n",
        "    Devuelve:\n",
        "        El teléfono del cliente guardado en el fichero o un mensaje de error si el teléfono o el fichero no existe.\n",
        "    '''\n",
        "    try: \n",
        "        f = open(file, 'r')\n",
        "    except FileNotFoundError:\n",
        "        return('¡El fichero ' + file + ' no existe!\\n')\n",
        "    else:\n",
        "        directory = f.readlines()\n",
        "        f.close()\n",
        "        directory = dict([tuple(line.split(',')) for line in directory])\n",
        "        if client in directory:\n",
        "            return directory[client]\n",
        "        else:\n",
        "            return('¡El cliente ' + client + ' no existe!\\n')\n",
        "\n",
        "\n",
        "def add_phone(file, client, telf):\n",
        "    '''\n",
        "    Función que añade el teléfono de un cliente de un fichero dado.\n",
        "    Parámetros:\n",
        "        file: Es un fichero con los nombres y teléfonos de clientes.\n",
        "        client: Es una cadena con el nombre del cliente.\n",
        "        telf: Es una cadena con el teléfono del cliente.\n",
        "    Devuelve:\n",
        "        Un mesaje informando sobre si el teléfono se ha añadido o ha habido algún problema.\n",
        "    '''\n",
        "    try: \n",
        "        f = open(file, 'a')\n",
        "    except FileNotFoundError:\n",
        "        return('¡El fichero ' + file + ' no existe!\\n')\n",
        "    else:\n",
        "        f.write(client + ',' + telf + '\\n')\n",
        "        f.close()\n",
        "        return('El teléfono se ha añadido.\\n')\n",
        "\n",
        "def remove_phone(file, client):\n",
        "    '''\n",
        "    Función que elimina el teléfono de un cliente de un fichero dado.\n",
        "    Parámetros:\n",
        "        file: Es un fichero con los nombres y teléfonos de clientes.\n",
        "        client: Es una cadena con el nombre del cliente.\n",
        "    Devuelve:\n",
        "        Un mesaje informando sobre si el teléfono se ha borrado o ha habido algún problema.\n",
        "    '''\n",
        "    try: \n",
        "        f = open(file, 'r')\n",
        "    except FileNotFoundError:\n",
        "        return('¡El fichero ' + file + ' no existe!\\n')\n",
        "    else:\n",
        "        directory = f.readlines()\n",
        "        f.close()\n",
        "        directory = dict([tuple(line.split(',')) for line in directory])\n",
        "        if client in directory:\n",
        "            del directory[client]\n",
        "            f = open(file, 'w')\n",
        "            for name, telf in directory.items():\n",
        "                f.write(name + ',' + telf)\n",
        "            f.close()\n",
        "            return ('¡El cliente se ha borrado!\\n')\n",
        "        else:\n",
        "            return('¡El cliente ' + client + ' no existe!\\n')\n",
        "\n",
        "\n",
        "def create_directory(file):\n",
        "    '''\n",
        "    Función que crea un fichero vacío para guardar un listín telefónico.\n",
        "    Parámetros:\n",
        "        file: Es un fichero.\n",
        "    Devuelve:\n",
        "        Un mesaje informando sobre si el fichero se ha creado correctamente o no.\n",
        "    '''\n",
        "    import os\n",
        "    if os.path.isfile(file):\n",
        "        answer = input('El fichero ' + file + ' ya existe. ¿Desea vaciarlo (S/N)? ')\n",
        "        if answer == 'N': \n",
        "            return 'No se ha creado el fichero porque ya existe.\\n'\n",
        "    f = open(file, 'w')\n",
        "    f.close()\n",
        "    return 'Se ha creado el fichero.\\n'\n",
        "     \n",
        "\n",
        "def menu():\n",
        "    '''\n",
        "    Función que presenta un menú con las operaciones disponibles sobre un listín telefónico y devuelve la opción seleccionada por el usuario.\n",
        "    Devuelve:\n",
        "        La opción seleccionada por el usuario.\n",
        "    '''\n",
        "    print('Gesión del listín telefónico')\n",
        "    print('============================')\n",
        "    print('1 - Consultar un teléfono')\n",
        "    print('2 - Añadir un teléfono')\n",
        "    print('3 - Eliminar un teléfono')\n",
        "    print('4 - Crear el listín')\n",
        "    print('0 - Terminar')\n",
        "    option = input('Introduzca el número de la opción deseada: ')\n",
        "    return option\n",
        "\n",
        "\n",
        "def directory():\n",
        "    '''\n",
        "    Función que lanza la aplicación para la gestión del listín telefónico.\n",
        "    '''\n",
        "    file = 'listin.txt' \n",
        "    while True:\n",
        "        option = menu()\n",
        "        if option == '1':\n",
        "            name = input('Introduce el nombre del cliente: ')\n",
        "            print(get_phone(file, name))\n",
        "        elif option == '2':\n",
        "            name = input('Introduce el nombre del cliente: ')\n",
        "            telf = input('Introduce el teléfono del cliente: ')\n",
        "            print(add_phone(file, name, telf))\n",
        "        elif option == '3':\n",
        "            name = input('Introduce el nombre del cliente: ')\n",
        "            print(remove_phone(file, name))\n",
        "        elif option == '4':\n",
        "            print(create_directory(file))\n",
        "        else:\n",
        "            break\n",
        "    return\n",
        "\n",
        "directory()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Gesión del listín telefónico\n",
            "============================\n",
            "1 - Consultar un teléfono\n",
            "2 - Añadir un teléfono\n",
            "3 - Eliminar un teléfono\n",
            "4 - Crear el listín\n",
            "0 - Terminar\n"
          ],
          "name": "stdout"
        }
      ]
    }
  ]
}